/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/models/room.gltf');
	return (
		<group ref={group} {...props} dispose={null}>
			<group position={[0, 4.1, 0]} scale={[4, 4, 4]}>
				<mesh
					receiveShadow
					geometry={nodes.Walls_1.geometry}
					material={materials.Material}
				/>
				<mesh
					receiveShadow
					geometry={nodes.Walls_2.geometry}
					material={materials.rama}
				/>
				<mesh
					receiveShadow
					geometry={nodes.Walls_3.geometry}
					material={materials.glass}
				/>
			</group>
			<mesh
				receiveShadow
				geometry={nodes.Carpet.geometry}
				material={materials.kover}
				position={[1.104228, 0.100004, -0.246547]}
				scale={[1.679434, 1.679434, 2.670468]}
			/>
			<group
				position={[3.278071, 0.907079, 1.781322]}
				rotation={[-0.732297, -1.482735, -0.686589]}
				scale={[0.55958, 0.55958, 0.179772]}>
				<mesh
					castShadow
					geometry={nodes.Sofa_1.geometry}
					material={materials['poduski.001']}
				/>
				<mesh
					castShadow
					geometry={nodes.Sofa_2.geometry}
					material={nodes.Sofa_2.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Sofa_3.geometry}
					material={materials.poduski}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf.geometry}
				material={nodes.Shelf.material}
				position={[-3.532094, 0.100005, 2.202697]}
			/>
			<mesh
				castShadow
				geometry={nodes.Table.geometry}
				material={nodes.Table.material}
				position={[-3.401579, 0.100019, -1.998935]}
			/>
			<group
				position={[3.060572, 0.099988, 3.348096]}
				scale={[0.37548, 0.37548, 0.37548]}>
				<mesh
					castShadow
					geometry={nodes.Plant_1.geometry}
					material={nodes.Plant_1.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Plant_2.geometry}
					material={materials.grass}
				/>
				<mesh
					castShadow
					geometry={nodes.Plant_3.geometry}
					material={materials.paporatnik}
				/>
			</group>
			<group
				position={[-1.38197, 3.761611, -3.999999]}
				scale={[0.145775, 0.145775, 0.145775]}>
				<mesh
					castShadow
					geometry={nodes.Window_1.geometry}
					material={nodes.Window_1.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Window_2.geometry}
					material={materials.sori}
				/>
			</group>
			<mesh
				castShadow
				geometry={nodes.Hexagons.geometry}
				material={nodes.Hexagons.material}
				position={[-3.999995, 3.768038, 3.242649]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[0.212198, 0.212198, 0.212198]}
			/>
			<group
				position={[-2.061255, 0.34991, -1.797221]}
				rotation={[0, 1.26935, 0]}
				scale={[0.106875, 0.106875, 0.106875]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Chair_1.geometry}
					material={nodes.Chair_1.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Chair_2.geometry}
					material={nodes.Chair_2.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Chair_3.geometry}
					material={materials['gamer torch']}
				/>
			</group>
			<group
				position={[-3.212876, 1.385985, -1.566323]}
				rotation={[0, 1.453947, 0]}
				scale={[0.622263, 0.622252, 0.186676]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Keyboard_1.geometry}
					material={materials.keys}
				/>
				<mesh
					castShadow
					geometry={nodes.Keyboard_2.geometry}
					material={nodes.Keyboard_2.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Keyboard_3.geometry}
					material={materials['keys red']}
				/>
			</group>
			<group
				position={[-2.978147, 1.385967, -0.652159]}
				rotation={[0, -1.461093, 0]}
				scale={[0.364394, 0.364394, 0.364394]}>
				<mesh
					castShadow
					geometry={nodes.Microphone_1.geometry}
					material={materials.shtativ}
				/>
				<mesh
					castShadow
					geometry={nodes.Microphone_2.geometry}
					material={nodes.Microphone_2.material}
				/>
			</group>
			<group
				position={[-3.819465, 2.247695, -1.895652]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[0.44237, 0.44237, 0.044237]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Monitor_1.geometry}
					material={materials.TW}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Monitor_2.geometry}
					material={<meshBasicMaterial attach='material' color={'#000'} />}
				/>
			</group>
			<group
				position={[-3.226014, 1.380978, -2.625078]}
				rotation={[-Math.PI, 1.370447, -Math.PI]}
				scale={[0.260055, 0.260055, 0.260055]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mouse_1.geometry}
					material={materials.mouse}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mouse_2.geometry}
					material={nodes.Mouse_2.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mouse_3.geometry}
					material={materials.Nvidea}
				/>
			</group>
			<group position={[-3.406284, 1.380976, -3.267619]}>
				<mesh
					castShadow
					geometry={nodes.PC_1.geometry}
					material={materials.iron}
				/>
				<mesh
					castShadow
					geometry={nodes.PC_2.geometry}
					material={materials.motherboard}
				/>
				<mesh
					castShadow
					geometry={nodes.PC_3.geometry}
					material={materials['Computer glass']}
				/>
			</group>
			<group
				position={[-3.203558, 1.306162, 0.527267]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={[-0.847114, 0.847114, 0.847114]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Books_1.geometry}
					material={materials['book.002']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Books_2.geometry}
					material={materials.book}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Books_3.geometry}
					material={materials['book.001']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Books_4.geometry}
					material={materials.skotulka}
				/>
			</group>
			<group
				position={[0.464457, 2.620021, -3.999984]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.596164, 0.920257, 0.808334]}>
				<mesh
					castShadow
					geometry={nodes.Posters_1.geometry}
					material={nodes.Posters_1.material}
				/>
				<mesh
					castShadow
					geometry={nodes.Posters_2.geometry}
					material={materials.plakat}
				/>
				<mesh
					castShadow
					geometry={nodes.Posters_3.geometry}
					material={materials['plakat.001']}
				/>
				<mesh
					castShadow
					geometry={nodes.Posters_4.geometry}
					material={materials['plakat.002']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/models/room.gltf');
